<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "user_auctions".
 *
 * @property int $id
 * @property int $user_id
 * @property string $price
 * @property string $file
 * @property string $status
 * @property int $auction_id
 *
 * @property Auctions $auction
 * @property User $user
 */
class UserAuctions extends \yii\db\ActiveRecord
{
    public $file1;
    const STATUS_WAIT = 0;
    const STATUS_ACTIVE = 10;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_auctions';
    }

    public function afterDelete()
    {
        if ($this->file !== null && !empty($this->file)) {
            unlink(Yii::getAlias('@backend').'/web/uploads/user-auctions/' . $this->file);
        }
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'price', 'auction_id'], 'required'],
            [['user_id', 'auction_id'], 'integer'],
            [['price', 'status'], 'string', 'max' => 255],
            [['auction_id'], 'exist', 'skipOnError' => true, 'targetClass' => Auctions::className(), 'targetAttribute' => ['auction_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['file'], 'string', 'max' => 255],
            [['file1'], 'file', 'skipOnEmpty' => false, 'extensions' => 'doc, docx, xls, xlsx, pdf']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'price' => Yii::t('app', 'Price'),
            'file' => Yii::t('app', 'File'),
            'status' => Yii::t('app', 'Status'),
            'auction_id' => Yii::t('app', 'Auction ID'),
        ];
    }



    public function upload()
    {
        if ($this->validate()) {
            $name = $this->file1->baseName . '_' . Yii::$app->security->generateRandomString(5) . '.' . $this->file1->extension;

            if ($this->file !== null && !empty($this->file)) {
                unlink(Yii::getAlias('@backend').'/web/uploads/user-auctions/' . $this->file);
            }
            $this->file = $name;
            $this->file1->saveAs(Yii::getAlias('@backend').'/web/uploads/user-auctions/' . $name);
            return true;
        } else {
            return false;
        }
    }

    /**
     * Gets query for [[Auction]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAuction()
    {
        return $this->hasOne(Auctions::className(), ['id' => 'auction_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function isWait()
    {
        return $this->status === self::STATUS_WAIT;
    }
    public function isActive()
    {
        return $this->status === self::STATUS_ACTIVE;
    }
}
